# Generated by Django 6.0.2 on 2026-02-25 18:54

from datetime import timedelta

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def set_default_expiry(apps, schema_editor):
    """Backfill expires_at for existing requests based on created_at + 7 days."""
    HelpRequest = apps.get_model('marketplace', 'HelpRequest')
    for request in HelpRequest.objects.filter(expires_at__isnull=True):
        if request.created_at:
            request.expires_at = request.created_at + timedelta(days=7)
        else:
            request.expires_at = timezone.now() + timedelta(days=7)
        request.save(update_fields=['expires_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='helprequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['request', 'is_private'], name='marketplace_request_a1310d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='marketplace_created_bdaad6_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='marketplace_slug_6a847e_idx'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='helprequests', to='marketplace.tag'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['expires_at'], name='marketplace_expires_473b20_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['status', 'expires_at'], name='marketplace_status_cbbca0_idx'),
        ),
        migrations.RunPython(set_default_expiry, migrations.RunPython.noop),
    ]
