# Generated by Django 6.0.2 on 2026-02-26 10:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_savedsearch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('payment_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly')], default='fixed', max_length=12)),
                ('budget_inr', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))])),
                ('escrow_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('disputed', 'Disputed')], default='open', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('response_sla_hours', models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_jobs_posted', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelance_jobs_taken', to=settings.AUTH_USER_MODEL)),
                ('skill_needed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.skill')),
                ('tags', models.ManyToManyField(blank=True, related_name='freelance_jobs', to='marketplace.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=12)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('against_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_disputes_received', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='marketplace.freelancejob')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_disputes_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('released', 'Released'), ('disputed', 'Disputed')], default='pending', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='marketplace.freelancejob')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('job_completed', 'Job Completed'), ('milestone_released', 'Milestone Released'), ('dispute_opened', 'Dispute Opened'), ('fraud_flag', 'Fraud Flag')], max_length=24)),
                ('score_delta', models.IntegerField()),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_signals', to='marketplace.freelancejob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=8)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('source_type', models.CharField(max_length=40)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='freelancejob',
            index=models.Index(fields=['status'], name='marketplace_status_9ef495_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancejob',
            index=models.Index(fields=['payment_type'], name='marketplace_payment_b82a15_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancejob',
            index=models.Index(fields=['skill_needed'], name='marketplace_skill_n_ef88d8_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancejob',
            index=models.Index(fields=['client'], name='marketplace_client__5bde57_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancejob',
            index=models.Index(fields=['freelancer'], name='marketplace_freelan_1338c1_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancejob',
            index=models.Index(fields=['created_at'], name='marketplace_created_10f976_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancejob',
            index=models.Index(fields=['status', 'created_at'], name='marketplace_status_fafcb0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdispute',
            index=models.Index(fields=['job'], name='marketplace_job_id_87aa02_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdispute',
            index=models.Index(fields=['status'], name='marketplace_status_373e49_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdispute',
            index=models.Index(fields=['created_at'], name='marketplace_created_c5194e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmilestone',
            index=models.Index(fields=['job', 'sequence'], name='marketplace_job_id_41bf76_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmilestone',
            index=models.Index(fields=['status'], name='marketplace_status_3c4184_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobmilestone',
            constraint=models.UniqueConstraint(fields=('job', 'sequence'), name='unique_job_milestone_sequence'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['user', 'status'], name='marketplace_user_id_8908bd_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['created_at'], name='marketplace_created_7cf219_idx'),
        ),
        migrations.AddIndex(
            model_name='trustsignal',
            index=models.Index(fields=['user', 'created_at'], name='marketplace_user_id_ab8316_idx'),
        ),
        migrations.AddIndex(
            model_name='trustsignal',
            index=models.Index(fields=['signal_type'], name='marketplace_signal__7fbece_idx'),
        ),
        migrations.AddIndex(
            model_name='walletledger',
            index=models.Index(fields=['user', 'created_at'], name='marketplace_user_id_7bbc92_idx'),
        ),
        migrations.AddIndex(
            model_name='walletledger',
            index=models.Index(fields=['source_type'], name='marketplace_source__d23107_idx'),
        ),
    ]
