# Generated by Django 6.0.2 on 2026-02-26 12:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_jobdispute_payout_amount_inr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceJobProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_note', models.TextField(blank=True)),
                ('proposed_total_inr', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=12)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_job_proposals', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='marketplace.freelancejob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreelanceJobProposalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='marketplace.freelancejobproposal')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequestProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_note', models.TextField(blank=True)),
                ('proposed_kp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=12)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_request_proposals', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='marketplace.helprequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='freelancejobproposal',
            index=models.Index(fields=['job', 'status'], name='marketplace_job_id_63a117_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancejobproposal',
            index=models.Index(fields=['applicant', 'status'], name='marketplace_applica_bdd0c4_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancejobproposal',
            index=models.Index(fields=['created_at'], name='marketplace_created_f08cbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='freelancejobproposal',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='unique_job_applicant'),
        ),
        migrations.AddIndex(
            model_name='freelancejobproposalmilestone',
            index=models.Index(fields=['proposal', 'sequence'], name='marketplace_proposa_331636_idx'),
        ),
        migrations.AddConstraint(
            model_name='freelancejobproposalmilestone',
            constraint=models.UniqueConstraint(fields=('proposal', 'sequence'), name='unique_job_proposal_sequence'),
        ),
        migrations.AddIndex(
            model_name='helprequestproposal',
            index=models.Index(fields=['request', 'status'], name='marketplace_request_ce2dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequestproposal',
            index=models.Index(fields=['applicant', 'status'], name='marketplace_applica_87ed0c_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequestproposal',
            index=models.Index(fields=['created_at'], name='marketplace_created_8509f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='helprequestproposal',
            constraint=models.UniqueConstraint(fields=('request', 'applicant'), name='unique_help_request_applicant'),
        ),
    ]
