# Generated by Django 6.0.2 on 2026-02-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_attachment_experiment_experimentassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
