# Generated by Django 6.0.2 on 2026-02-27 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_helprequest_ai_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_type', models.CharField(choices=[('request', 'Request'), ('job', 'Paid Job'), ('workspace', 'Workspace')], max_length=12)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads_created', to=settings.AUTH_USER_MODEL)),
                ('help_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread', to='marketplace.helprequest')),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread', to='marketplace.freelancejob')),
                ('workspace', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread', to='marketplace.workspace')),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatThreadParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='marketplace.chatthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='chatthread',
            name='participants',
            field=models.ManyToManyField(related_name='chat_threads', through='marketplace.ChatThreadParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.chatthread')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread', 'created_at'], name='marketplace_thread__01ad82_idx'), models.Index(fields=['sender', 'created_at'], name='marketplace_sender__d01cc1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatthreadparticipant',
            index=models.Index(fields=['user', 'last_read_at'], name='marketplace_user_id_cdd70a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthreadparticipant',
            index=models.Index(fields=['thread', 'last_read_at'], name='marketplace_thread__636b85_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatthreadparticipant',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='unique_chat_thread_user'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['thread_type'], name='marketplace_thread__d88767_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['last_message_at'], name='marketplace_last_me_146217_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['created_at'], name='marketplace_created_5e24b6_idx'),
        ),
    ]
