# Generated by Django 6.0.2 on 2026-02-27 06:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_chatthread_chatthreadparticipant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('key', models.CharField(max_length=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_projects_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='marketplace.workspace')),
            ],
            options={
                'ordering': ['workspace__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='todo', max_length=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('estimate_points', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_issues_assigned', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_issues_reported', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='marketplace.workspaceproject')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceIssueActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('from_value', models.CharField(blank=True, max_length=120)),
                ('to_value', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_issue_actions', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='marketplace.workspaceissue')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue', 'created_at'], name='marketplace_issue_i_3659f0_idx'), models.Index(fields=['actor', 'created_at'], name='marketplace_actor_i_b269a0_idx'), models.Index(fields=['action'], name='marketplace_action_e51065_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workspaceproject',
            index=models.Index(fields=['workspace', 'is_active'], name='marketplace_workspa_397350_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceproject',
            index=models.Index(fields=['workspace', 'key'], name='marketplace_workspa_4b04c7_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceproject',
            index=models.Index(fields=['created_at'], name='marketplace_created_f0f782_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspaceproject',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='unique_workspace_project_key'),
        ),
        migrations.AddIndex(
            model_name='workspaceissue',
            index=models.Index(fields=['project', 'status'], name='marketplace_project_8426fe_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceissue',
            index=models.Index(fields=['project', 'priority'], name='marketplace_project_d75611_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceissue',
            index=models.Index(fields=['assignee', 'status'], name='marketplace_assigne_90d2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceissue',
            index=models.Index(fields=['due_date'], name='marketplace_due_dat_bcd488_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceissue',
            index=models.Index(fields=['created_at'], name='marketplace_created_bee9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceissue',
            index=models.Index(fields=['updated_at'], name='marketplace_updated_6898f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspaceissue',
            constraint=models.UniqueConstraint(fields=('project', 'issue_number'), name='unique_project_issue_number'),
        ),
    ]
