# Generated by Django 6.0.2 on 2026-02-27 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_workspaceproject_workspaceissue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceIssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_issue_comments', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='marketplace.workspaceissue')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('goal', models.CharField(blank=True, max_length=220)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_sprints_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='marketplace.workspaceproject')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workspaceissue',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='marketplace.workspacesprint'),
        ),
        migrations.AddIndex(
            model_name='workspaceissue',
            index=models.Index(fields=['project', 'sprint'], name='marketplace_project_3bc7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceissuecomment',
            index=models.Index(fields=['issue', 'created_at'], name='marketplace_issue_i_d09ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceissuecomment',
            index=models.Index(fields=['author', 'created_at'], name='marketplace_author__c9ce69_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacesprint',
            index=models.Index(fields=['project', 'status'], name='marketplace_project_04af42_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacesprint',
            index=models.Index(fields=['start_date', 'end_date'], name='marketplace_start_d_0a9099_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacesprint',
            index=models.Index(fields=['created_at'], name='marketplace_created_71dc5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacesprint',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_sprint_name'),
        ),
    ]
