# Generated by Django 6.0.2 on 2026-03-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_workspaceissuecomment_workspacesprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
