# Generated by Django 6.0.2 on 2026-05-12 13:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_feature_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='point_value_inr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Payout amount per completed Jira point', max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobmilestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('submitted', 'Submitted'), ('released', 'Released'), ('disputed', 'Disputed')], default='pending', max_length=12),
        ),
    ]
