# Generated by Django 6.0.2 on 2026-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_workspace_point_value_inr_alter_jobmilestone_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancejob',
            name='fee_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freelancejobproposal',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helprequestproposal',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
