# Generated by Django 6.0.2 on 2026-05-12 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_freelancejob_fee_waived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPPerkPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perk_type', models.CharField(choices=[('highlight_proposal', 'Highlight a Proposal'), ('waive_job_fee', 'Waive Platform Fee on Job')], max_length=40)),
                ('kp_cost', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perk_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'perk_type'], name='marketplace_user_id_823aed_idx'), models.Index(fields=['is_active'], name='marketplace_is_acti_fcd1a2_idx')],
            },
        ),
    ]
