# Generated by Django 6.0.2 on 2026-02-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options'),
        ('marketplace', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='marketplace.skill'),
        ),
    ]
