# Generated by Django 6.0.2 on 2026-02-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_skills'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('marketplace', '0005_tag_helprequest_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_kp_claim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['knowledge_points'], name='accounts_cu_knowled_bebf4b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['last_kp_claim'], name='accounts_cu_last_kp_6a91c6_idx'),
        ),
    ]
