# Generated by Django 6.0.2 on 2026-02-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_last_kp_claim_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('marketplace', '0006_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification_preference',
            field=models.CharField(choices=[('both', 'In-app + Email'), ('in_app', 'In-app only'), ('email', 'Email only'), ('none', 'Disable all')], default='both', max_length=12),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['notification_preference'], name='accounts_cu_notific_c91332_idx'),
        ),
    ]
