# Generated by Django 6.0.2 on 2026-02-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_notification_preference_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('marketplace', '0007_freelancejob_jobdispute_jobmilestone_payoutrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='compliance_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['wallet_inr'], name='accounts_cu_wallet__bb8cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['compliance_verified'], name='accounts_cu_complia_46c8e0_idx'),
        ),
    ]
