# Generated by Django 6.0.2 on 2026-02-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_compliance_verified_customuser_wallet_inr_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('marketplace', '0009_freelancejobproposal_freelancejobproposalmilestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ui_density',
            field=models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=12),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['ui_density'], name='accounts_cu_ui_dens_526f4b_idx'),
        ),
    ]
