# Generated by Django 6.0.2 on 2026-02-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_ui_density_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('marketplace', '0009_freelancejobproposal_freelancejobproposalmilestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_suspended'], name='accounts_cu_is_susp_0fec2b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['suspended_until'], name='accounts_cu_suspend_33cc11_idx'),
        ),
    ]
