# Generated by Django 6.0.2 on 2026-02-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_suspended_customuser_suspended_until_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('marketplace', '0010_attachment_experiment_experimentassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trust_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trust_score_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['trust_score'], name='accounts_cu_trust_s_8441de_idx'),
        ),
    ]
