# Generated by Django 6.0.2 on 2026-03-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auditlog'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('marketplace', '0014_workspaceissuecomment_workspacesprint_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('knowledge_points__gte', 0)), name='customuser_kp_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('wallet_inr__gte', 0)), name='customuser_wallet_non_negative'),
        ),
    ]
