# Generated by Django 6.0.2 on 2026-03-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_balance_check_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_chat',
            field=models.BooleanField(default=True, help_text='Receive notifications about chat messages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_jobs',
            field=models.BooleanField(default=True, help_text='Receive notifications about freelance jobs'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_kp',
            field=models.BooleanField(default=True, help_text='Receive notifications about KP transfers'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_requests',
            field=models.BooleanField(default=True, help_text='Receive notifications about help requests'),
        ),
    ]
