from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import advanced_views, chat_views, jira_views, views

router = DefaultRouter()
router.register(r'requests', views.HelpRequestViewSet, basename='request')
router.register(r'jobs', views.FreelanceJobViewSet, basename='api-job')
router.register(r'users', views.UserViewSet, basename='api-user')
router.register(r'skills', views.SkillViewSet, basename='api-skill')
router.register(r'workspace-projects', views.WorkspaceProjectViewSet, basename='api-workspace-project')
router.register(r'workspace-issues', views.WorkspaceIssueViewSet, basename='api-workspace-issue')

urlpatterns = [
    path('', views.home, name='home'),
    path('browse/', views.request_list, name='request_list'),
    path('search/', views.unified_search, name='search'),
    path('chat/', chat_views.chat_inbox, name='chat_inbox'),
    path('chat/thread/<int:thread_id>/', chat_views.chat_thread_detail, name='chat_thread_detail'),
    path('feed/', views.activity_feed, name='activity_feed'),
    path('saved-searches/', views.saved_searches, name='saved_searches'),
    path('saved-searches/save-current/', views.save_current_search, name='save_current_search'),
    path('saved-searches/<int:pk>/toggle/', views.toggle_saved_search, name='toggle_saved_search'),
    path('saved-searches/<int:pk>/delete/', views.delete_saved_search, name='delete_saved_search'),
    path('recommendations/', advanced_views.recommendations, name='recommendations'),
    path('jobs/', views.freelance_job_list, name='freelance_job_list'),
    path('jobs/post/', views.post_freelance_job, name='post_freelance_job'),
    path('jobs/<int:pk>/', views.freelance_job_detail, name='freelance_job_detail'),
    path('jobs/<int:pk>/propose/', views.submit_job_proposal, name='submit_job_proposal'),
    path('jobs/<int:pk>/proposals/<int:proposal_id>/select/', views.select_job_proposal, name='select_job_proposal'),
    path('jobs/<int:pk>/proposals/compare/', advanced_views.compare_job_proposals, name='compare_job_proposals'),
    path('jobs/<int:pk>/proposals/withdraw/', views.withdraw_job_proposal, name='withdraw_job_proposal'),
    path('jobs/<int:pk>/chat/', chat_views.job_chat, name='job_chat'),
    path('jobs/<int:pk>/claim/', views.claim_freelance_job, name='claim_freelance_job'),
    path('jobs/<int:pk>/milestones/add/', views.add_job_milestone, name='add_job_milestone'),
    path('jobs/<int:pk>/milestones/<int:milestone_id>/submit/', views.submit_job_milestone, name='submit_job_milestone'),
    path('jobs/<int:pk>/milestones/<int:milestone_id>/deliverable/', advanced_views.submit_milestone_deliverable, name='submit_milestone_deliverable'),
    path('jobs/<int:pk>/milestones/<int:milestone_id>/revision/', advanced_views.request_milestone_revision, name='request_milestone_revision'),
    path('jobs/<int:pk>/milestones/<int:milestone_id>/approve/', advanced_views.approve_milestone_deliverable, name='approve_milestone_deliverable'),
    path('jobs/<int:pk>/milestones/<int:milestone_id>/release/', views.release_job_milestone, name='release_job_milestone'),
    path('jobs/<int:pk>/dispute/', views.open_job_dispute, name='open_job_dispute'),
    path('jobs/<int:pk>/cancel/', views.cancel_freelance_job, name='cancel_freelance_job'),
    path('wallet/', views.wallet_overview, name='wallet_overview'),
    path('wallet/export/', views.export_wallet_ledger_csv, name='wallet_export_csv'),
    path('jobs/disputes/export/', views.export_job_disputes_csv, name='job_disputes_export_csv'),
    path('post/assist/', views.ai_request_assist, name='ai_request_assist'),
    path('post/', views.create_request, name='create_request'),
    path('request/<int:pk>/', views.request_detail, name='request_detail'),
    path('request/<int:pk>/edit/', views.edit_request, name='edit_request'),
    path('request/<int:pk>/delete/', views.delete_request, name='delete_request'),
    path('request/<int:pk>/rate/', views.rate_request, name='rate_request'),
    path('request/<int:pk>/propose/', views.submit_request_proposal, name='submit_request_proposal'),
    path('request/<int:pk>/proposals/<int:proposal_id>/select/', views.select_request_proposal, name='select_request_proposal'),
    path('request/<int:pk>/proposals/compare/', advanced_views.compare_request_proposals, name='compare_request_proposals'),
    path('request/<int:pk>/proposals/withdraw/', views.withdraw_request_proposal, name='withdraw_request_proposal'),
    path('request/<int:pk>/chat/', chat_views.request_chat, name='request_chat'),
    path('request/<int:pk>/claim/', views.claim_request, name='claim_request'),
    path('request/<int:pk>/resolve/', views.resolve_request, name='resolve_request'),
    path('request/<int:pk>/cancel/', views.cancel_request, name='cancel_request'),
    path('skills/', views.skill_browse, name='skill_browse'),
    path('tags/', views.tag_browse, name='tag_browse'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('portfolio/', advanced_views.manage_portfolio, name='manage_portfolio'),
    path('portfolio/<int:item_id>/delete/', advanced_views.delete_portfolio_item, name='delete_portfolio_item'),
    path('workspaces/', advanced_views.workspace_list, name='workspace_list'),
    path('workspaces/<slug:slug>/', advanced_views.workspace_detail, name='workspace_detail'),
    path('workspaces/<slug:slug>/chat/', chat_views.workspace_chat, name='workspace_chat'),
    path('workspaces/<slug:slug>/projects/', jira_views.workspace_projects, name='workspace_projects'),
    path(
        'workspaces/<slug:slug>/projects/<int:project_id>/',
        jira_views.workspace_project_board,
        name='workspace_project_board',
    ),
    path(
        'workspaces/<slug:slug>/projects/<int:project_id>/issues/new/',
        jira_views.workspace_issue_create,
        name='workspace_issue_create',
    ),
    path(
        'workspaces/<slug:slug>/projects/<int:project_id>/issues/<int:issue_id>/',
        jira_views.workspace_issue_detail,
        name='workspace_issue_detail',
    ),
    path(
        'workspaces/<slug:slug>/projects/<int:project_id>/issues/<int:issue_id>/edit/',
        jira_views.workspace_issue_edit,
        name='workspace_issue_edit',
    ),
    path(
        'workspaces/<slug:slug>/projects/<int:project_id>/issues/<int:issue_id>/transition/',
        jira_views.workspace_issue_transition,
        name='workspace_issue_transition',
    ),
    path(
        'workspaces/<slug:slug>/projects/<int:project_id>/sprints/create/',
        jira_views.workspace_sprint_create,
        name='workspace_sprint_create',
    ),
    path(
        'workspaces/<slug:slug>/projects/<int:project_id>/sprints/<int:sprint_id>/start/',
        jira_views.workspace_sprint_start,
        name='workspace_sprint_start',
    ),
    path(
        'workspaces/<slug:slug>/projects/<int:project_id>/sprints/<int:sprint_id>/complete/',
        jira_views.workspace_sprint_complete,
        name='workspace_sprint_complete',
    ),
    path('workspaces/<slug:slug>/invite/', advanced_views.workspace_invite_member, name='workspace_invite_member'),
    path('workspaces/<slug:slug>/deposit/', advanced_views.workspace_deposit, name='workspace_deposit'),
    path('workspaces/<slug:slug>/withdraw/', advanced_views.workspace_withdraw, name='workspace_withdraw'),
    path('integrations/', advanced_views.integrations_settings, name='integrations_settings'),
    path('integrations/api-keys/<int:key_id>/revoke/', advanced_views.revoke_api_key, name='revoke_api_key'),
    path('integrations/webhooks/<int:endpoint_id>/delete/', advanced_views.delete_webhook, name='delete_webhook'),
    path('integrations/webhooks/<int:endpoint_id>/test/', advanced_views.test_webhook, name='test_webhook'),
    path('moderation/', advanced_views.moderation_console, name='moderation_console'),
    path('moderation/flag/<str:target_type>/<int:target_id>/', advanced_views.report_content, name='report_content'),
    path('moderation/flags/<int:pk>/<str:action>/', advanced_views.moderation_flag_action, name='moderation_flag_action'),
    path('moderation/users/<int:user_id>/suspend/', advanced_views.suspend_user_account, name='suspend_user_account'),
    path('moderation/users/<int:user_id>/unsuspend/', advanced_views.unsuspend_user_account, name='unsuspend_user_account'),
    path('analytics/advanced/', advanced_views.advanced_analytics, name='advanced_analytics'),
    path('api/me/live-status/', advanced_views.live_nav_status, name='live_nav_status'),
    path('ops/celery/', advanced_views.ops_celery_status, name='ops_celery_status'),
    path('ops/webhooks/', advanced_views.ops_webhook_status, name='ops_webhook_status'),
    path('ops/runtime/', advanced_views.ops_runtime_status, name='ops_runtime_status'),
    path('trust-score/', advanced_views.trust_score_breakdown, name='trust_score_breakdown_self'),
    path('trust-score/<str:username>/', advanced_views.trust_score_breakdown, name='trust_score_breakdown'),
    path('experiments/', advanced_views.experiment_console, name='experiment_console'),
    path('attachments/<str:target_type>/<int:target_id>/upload/', advanced_views.upload_attachment, name='upload_attachment'),
    path('u/<str:username>/portfolio/', advanced_views.public_portfolio, name='public_portfolio'),
    path('request/<int:pk>/recommended-helpers/', advanced_views.recommended_helpers, name='recommended_helpers'),
    path(
        'workspaces/<slug:slug>/projects/<int:project_id>/sprints/<int:sprint_id>/burndown/',
        advanced_views.sprint_burndown_data,
        name='sprint_burndown_data',
    ),
    path('api/search/', views.SearchViewSet.as_view({'get': 'list'}), name='api-search'),
    path('api/', include(router.urls)),
]

